name: CD - Docker Hub (on PR to main)

on:
  pull_request:
    branches: [ main ]

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/checkpoint5-api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build JAR
        run: mvn -B -ntp -DskipTests clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push (PR tag)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:pr-${{ github.event.number }}
            ${{ env.IMAGE_NAME }}:pr-${{ github.event.number }}-${{ github.sha }}
