name: CI - Maven Build & Test

on:
  push:
    branches:
      - develop
      - 'feature/**'
      - 'hotfix/**'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Unit tests
        run: mvn -B -ntp test

      - name: Package (fat-jar)
        run: mvn -B -ntp -DskipTests clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
